* TODO emacs
** Get any files titled 'TODO' to open automatically in org-mode (completed. just add ".org" to the end of the filename. I can also look into how to do this without the extension)
** Get at least this particular file to open automatically in auto-fill-mode (apparently it doesn't wrap text when in a bullet)
** Get any .cpp files to open in auto-fill-mode
** Checkmarks/status
* TODO Programming
** C++
*** Misc
**** Go through stackoverflow and look at some of the questions and figure out how the code that I don't understand works
*** SDL
**** Figure out how to center objects onto the screen
**** Add a list of required libs necessary to run the program
     
** Java
** Languages to learn
*** Clojure
*** Rust
*** Node.js
* TODO Linux
** Commands
*** chmod
*** chgrp
*** chown
*** apt
**** apt-cache
**** apt-add-repository
** Installing from source
*** Holy cow, I have had so many issues with trying to install
stuff. Usually, I just end up randomly installing stuff and I don't
even know where it goes or how to fix it. I especially had alot of
issues when I was trying to load a png file in my SDL test. I need to
figure this stuff out so I can better debug issues in the future

*** For the most part, if you are install from source, the general
steps to take are as follows:
- ./configure
- make
- make install

** OS errors
*** Investigate how apport works. Possibly create a script to
autoremove all files in /var/crash/

** Email
** Automation/Backups

I don't want to have to put my .emacs on my github repo. I can, but
for the purposes I will be using it for, it will be annoying to have
to clone my repo everytime I want the file. Or just copy and paste the
file.

The solution for now will be to auto back it up every week or so to my NAS.
*** Eventually consider creating my own personal email server. At the
time, the complexity outweighs the benefits
* TODO Miscellaneous
** Internet
*** Automatically import Chrome bookmarks to Firefox browser every
day, maybe less frequently.

