#+TITLE: My (Potential) Game - Notes
* Game Details
** Name (as requested by Sebastian)
Save The Star Kingdom
** Levels
*** Boss
Some final boss - again, suggested by Sebastian
* Code structure
** Classes
*** Shader Class
To create and combine the vertex and fragment shaders
*** VAO Class
To create VAOs and to add VBOs
*** VBO Class
Each game item will have at least two VBOs associated with it: the item's coordinates and its colors
**** Coords
**** Colors
*** Game State Class
There will have to be a way to determine what state the game is in. Depending on the state will determine what's on the screen and how to update the items
*** Image Class
Each item that is displayed in the game will be an image class at its core. Depending on what it is will determine what kind of subclass it is
**** Menu Class
 The game will have menu items all over the place for when you start the game, pause the game, etc. This class will contain the details of the menu item. It will probably inherit from a parent ?Image? class
***** Members
****** Text
 The menu item will have some text to display
