#+TITLE: Hello world

/Note: Sometimes I will be taking notes from the emacs Editor Manual./
/If I want to return to a specific poriton in the manual, I will create a bookmark (C-x r b)/
/At the top of the section I am taking notes on, I will give the name of the bookmark/

* Emacs major/minor modes

** Themes
*** Color theme
**** If you load this file to a new distro without the color theme
addon installed, it's simply added by installing emacs-goodies-el:

sudo apt-get install emacs-goodies-el

*** Require the color-theme package.

After installing Color Theme, you can pick and choose from a menu. This menu can be accessed via ‘M-x color-theme-select’

To start emacs with the selected theme as default, change the 'color-theme-...' in the .emacs file

*** List of favorite themes
- Bharadwaj Slate
- Alice Blue
- Calm Forest
- Charcoal Black
- Classic
- Comidia
- Dark Blue
- Dark Blue 2
- Deep Blue
- Gnome
- Gnome 2
- Gray30
- Green Kingsajz
- Jonabadian Slate
- Matrix
- Montz
- Renegade
- Resolve
- Retro Orange
- Robin Hood
- Shaman
- Sitaram Solaris
- Snow
- Subtle Blue
- Subtle Hacker
- Taming Mr Arneson
- Taylor
- White on Grey
- XP

** DocView
Used to view PDFs and other file types
  
Some basic stuff to help w/ navigation. See info file for actual documentation

To skip to next page type 'n'. To go to previous page type 'p'

To enlarge or shrink the page, type '+' or '-' respetively
** flyspell-mode
Underline incorrectly spelled text

There are several options (see manual).

You can use several other minor modes which are similar that have
quite a bit of flexibility depending on what you want to do

* Misc 
** General
Filepath copy
 If you want to copy the current file path (including the filename) a
 shortcut is to just go to the *Messages* buffer after having saved
 said file and just copy the output.

 This is useful for if you want to create a link to a file in org mode
 for instance.

** Commands
M-: to evaluate a command
 A useful command to evaluate is "buffer-file-name". This will output
 the file path (+ filename) into the minibuffer. I have yet to figure
 out how to actually copy the minibufer text...
