#+TITLE: General NOTES on various computer/programming/Linux related topics

* Scripts
** Backup script
See https://help.ubuntu.com/lts/serverguide/backup-shellscripts.html 
for a useful guide on creating a backup script and how to automate it
with a cron job

* Cronjob
See https://askubuntu.com/questions/2368/how-do-i-set-up-a-cron-job
for a simple description of how to do cronjobs
* Commands
** touch
 Adds some file or dir to the current dir. As opposed to opening a new
 file with a program

** grep
 Use to search directory for a phrase. For example:
  grep -rnw '/' -e 'word'
  
 searches the current directory recursively (-r), shows the line
 number in the file where the phrase is found (-n) which matches the
 whole word (-w)

 See
 https://stackoverflow.com/questions/16956810/how-do-i-find-all-files-containing-specific-text-on-linux

** pwd
 Print the current directory

** uname -r
 (prints "2.6.22-14-generic" for example)

 Use to check the kernel version where,

 - 2 : Kernel version
 - 6 : The major revision of the kernel
 - 22 : The minor revision of the kernel
 - 14 : Immediate fixing / bug fixing for critical error
 - generic : Distribution specific sting. For example, Redhat appends
string such as EL5 to indicate RHEL 5 kernel.

** find
Use the following syntax to search for a file:

find /home/username/ -name "*.err"
* Directories
/bin
 In either the linux fs or the application context, bin is just short
 for binaries

 In the downloaded application context, /bin is where the application
 stores its binaries (duh).

 In the linux fs context, this is where most of the system application
 binaries reside. Not exactly sure on the difference between this dir
 and the /usr/bin dir. At this point it's not that important

 See this link for more
 https://unix.stackexchange.com/questions/5915/difference-between-bin-and-usr-bin

* Installation
 For the most part, if you are install from source, the general steps
 to take are as follows:

- ./configure
- make
- make install
